---
- name: Playbook for Deploying an NFS server
  hosts: servera
  tasks:
  - name: Including a variable file
    include_vars: nfs_env.yml

  - name: Including a task file    
    include: nfs_tasks.yml


