---
- name: Play for deploying an NFS server
  hosts: mariadb,haproxy 
  user: devops
  become: yes
  become_method: sudo
  become_user: root
  #vars:
  #  pkg: nfs-utils.x86_64
  
  #vars_files:
  #- env.yml

  tasks:
  - name: "Installing {{ pkg }} related pkgs"
    yum:
      name: "{{ pkg }}"
      state: latest
